theme: minima
title: rykerr medical llc
description: cool stuff for clinicians
author: rykerr
url: "https://www.rykerrmedical.com"
baseurl: ""
include:
  - clinical-resources

markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true

plugins:
  - jekyll-feed
feed:
  path: blog-feed.xml
