[build]
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . -- ':!netlify/'"

[functions]
  directory = "netlify/functions"
